# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

entries = Entry.create([{title: "Callisto's Character Type Isn't All That Inventive", season: 1, episode: 22, response_to: "Your comments about Callisto's character being extremely well-crafted", comment: "Callisto is an incredible character, but she is also quite boring in the archetypal character sense. This is because she clearly fits the archetype of `inverse of main character` that is so tired and overdone. While Callisto is great, Hudson is an incredible actor, and both are rightly beloved, the actual conception of the character from a unique storybuilding standpoint has a significant element of failure.", sources: "None."}, {title: "Plot devices -- Gabrielle's Unbelievable Pain", season: 6, episode: 4, response_to: "A trend I noticed...", comment: "Ever notice how some of the gutwrenching episodes of this show hinge upon a completely out-of-nowhere death in Gabrielle's family that takes a lot of suspension of disbelief to accept as character-consistent? Think `Who's Gurkhan`, `Return of Callisto`...", sources: "None."}, {title: "The Vanishing Brother", season: 1, episode: 23, response_to: "Toris", comment: "We all know that Toris was quietly disappeared from the show after the terrible tragedy that was Death Mask.... but what did this do to the show's continuity? Does Toris exist, and is just never mentioned again, or must we conclude that he never existed and has been written out of the Xenaverse? Well, I argue that it's very in-character for Xena to let go of a brother and never bring him up again... especially if she never did before.", sources: "None."}, {title: "The Worst Episode", season: 5, episode: 10, response_to: "Terrible floating red skies of nowhere", comment: "Lyre, Lyre, Hearts on Fire is the worst episode of Xena: Warrior Princess. Sure, there are less engaging episodes, and more frustrating ones, but none so incomprehensible as this one. What I care about, however, is *why*. The answer is simple: It's the 100th episode! Celebration! The whole team clearly had fun with this one, and it cost them all coherenc.", sources: "Xena Warrior Podcast with Katie, Vera, and Livy"}])
